export const fonts = [
  'YOU',
  'US Angel',
  'The Amazing Spider-Man',
  'Spongebob',
  'Soulmate',
  'Sayyeda',
  'Qetod',
  'Power Rangers',
  'Plain Black Wide',
  'One Piece',
  'Old English Five',
  'Ninja Naruto',
  'Mostwasted',
  'Marvel',
  'Impostograph',
  'Homoarakhn',
  'Harry Potter',
  'Genshin Impact DRIP FONT',
  'Game of Thrones',
  'Gabriel',
  'Fette Classic UNZ Fraktur',
  'Ditty',
  'Death Font',
  'CrushNBurn',
  'Cloister Black',
  'ARB 85 Poster Script',
  'Among Us',
];
